version: '3.4'

services:
  ycompany.identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SqlConnection=Server=db;Initial Catalog=YCompany.Microservice.IdentityDb;User Id=sa;Password=Djhsd12jk
    ports:
      - "9000:80"
      - "9001:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  
  ycompany.claim.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SqlConnection=Server=db1;Initial Catalog=YCompany.Microservice.ClaimDb;User Id=sa;Password=Djhsd12jk
      - EventBusHostName=rabbit
    ports:
      - "9002:80"
      - "9003:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ycompany.notification.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventBusHostName=rabbit
    ports:
      - "9004:80"
      - "9005:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ycompany.webgateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9050:80"
      - "9051:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  
