version: '3.4'

services:
  ycompany.identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9000:80"
      - "9001:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro