// <auto-generated />
using System;
using Claim;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Claim.Migrations
{
    [DbContext(typeof(ClaimDbContext))]
    [Migration("20210117170956_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Claim.Models.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyCustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9eb7b968-f55e-4b3b-9c34-ff6a777dce0c"),
                            PolicyCustomerId = new Guid("3d460ad8-b566-49ef-a1f6-e44bd5b641f5"),
                            PolicyId = new Guid("ef52bd90-5769-407e-a357-6d9fa8b6172a"),
                            RegisterDate = new DateTime(2021, 1, 17, 22, 39, 55, 834, DateTimeKind.Local).AddTicks(1357),
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
