// <auto-generated />
using System;
using Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Identity.Migrations
{
    [DbContext(typeof(IdentityDBContext))]
    partial class IdentityDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Identity.Models.PolicyCustomer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("PolicyCustomers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("3d460ad8-b566-49ef-a1f6-e44bd5b641f5"),
                            FirstName = "Pankaj"
                        },
                        new
                        {
                            CustomerId = new Guid("2c59df60-7495-4152-bacf-58c92595f676"),
                            FirstName = "Pooja"
                        },
                        new
                        {
                            CustomerId = new Guid("19ea5298-053e-48f6-96fe-b19fa041268c"),
                            FirstName = "Neha"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
